spring:
  application:
    name: ribbon-consumer
server:
  port: 3337

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:${eureka.port:1111}/eureka/